### PR TITLE
Fix custom plugin default command overriding

### PR DESCRIPTION
**Pull request by arthuralmeidap**
@artf ,
  Here is my fix. Take a look and tell me what you think.

### CODE REVIEW

**Comment by arthuralmeidap** [comment]
I forgot to mention but this PR is related for the issue #355

**Comment by artf** [comment]
Hi Arthur and thanks for the contribution, by the way, I can't accept it as it's important that `onLoad`  triggers after plugins and the reason is just above in the comment
```js
// Execute `onLoad` on modules once all plugins are initialized.
// A plugin might have extended/added some custom type so this
// is a good point to load stuff like components, css rules, etc.
```
If you want to fix 'default command overriding' I'd suggest you try to move `onLoad()` at the end of  `init()` (in https://github.com/artf/grapesjs/blob/dev/src/commands/index.js)

**Comment by arthuralmeidap** [comment]
Hi @artf,
  Don't worry, I saw the comment but when I ran the tests and everything went fine, I give a try for this PR.
  Unfortunately, your suggestion won't work either because the modules are being loaded after the plugins.
  One question: Why can't the Command Module load the default commands on init? I have a solution using this approach but one of the tests says : "Main Commands - No default commands on init" and it fails.. 
  Looking forward to hear from you

**Comment by artf** [comment]
> Why can't the Command Module load the default commands on init?

This is exactly what I meant with `If you want to fix 'default command overriding' I'd suggest you try to move onLoad() at the end of init()` 😄 
```js
init() {
    ...
    this.loadDefaultCommands(); // this is all the content from onLoad
    return this;   
}

// Remove onLoad
onLoad() {
    ...
```

**Comment by arthuralmeidap** [comment]
Hi @artf ,
  I did what you suggested. Look and tell what you think about it.
  All commands are loaded at the end of Command init  and removed toLoad property to not override again the default commands.

**Comment by artf** [comment]
Great 👍 , can you just bring `editor.getModel().loadOnStart();` under the plugin loader then I can merge

**Comment by arthuralmeidap** [comment]
Ops, sorry! Fixed now!

**Comment by artf** [comment]
Thanks Arthur ❤️

**Pull request merged**
