### PR TITLE
Feature/updated npm

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by artf** [comment]
Hi Denis, can you leave the webpack file as it is?

**Comment by Piterden** [comment]
Ya, sure

**Comment by Piterden** [comment]
Like this?

**Comment by artf** [comment]
Thanks Denis, but one more thing. Why do we need [`babel-eslint`](https://github.com/babel/babel-eslint#why-use-babel-eslint)?
When you push a PR you should avoid the `build` command otherwise we get useless conflicts with `dist` files

**Comment by artf** [comment]
Update deps with the latest version

**Pull request closed without merging**
