### PR TITLE
bugfix(1914) Change REM to EM

### PR DESCRIPTION
**Pull request by lyczos**
#1914 Changed all REM units to EM units.

### CODE REVIEW

**Comment by lyczos** [comment]
@artf any info updates on this? :)

**Comment by artf** [comment]
Hi @lyczos sorry for the late response. BTW would you like to check how to solve the issue in the block panel?
Schermata 2019-04-13 alle 18 22 32
I mean, I know what is happening but I'm not really sure how to solve it.
For example:
- The Text block is the standard behavior and is ok
- Link and Video have `fa` custom class on top (from the block definition I'm able to pass custom classes for the ) which has another font-size (but take always in consideration that the user can pass its own classes with other sizes)
- Form and input blocks are with a nested `gjs-block-label` class 😬

**Comment by lyczos** [comment]
@artf sure, I will look into it.

**Comment by larsdecker** [comment]
Any news about this topic?

For projects that will include GrapesJS as a Library, the changes will be good.

**Pull request closed without merging**
