### PR TITLE
Updated ToolbarButtonView to render title attribute if present

### PR DESCRIPTION
**Pull request by thecodefish**
If any components specify custom toolbar options, you can include a title attribute. This attribute will now be rendered as an html title, allowing you to give a short description on what the toolbar button actually does.

This change just renders the title attribute (if it exists), it doesn't modify the default toolbars at all.

### CODE REVIEW

**Comment by thecodefish** [comment]
Example config:

```
...
toolbar: [
  {
    attributes: { 'class': 'fa fa-pencil', title: 'Configure this Widget' },
    command: 'myCustomCommand'
  },
  {
    attributes: { 'class': 'fa fa-arrows', title: 'Move Widget' },
   command: 'tlb-move'
  },
  {
    attributes: { 'class': 'fa fa-clone', title: 'Clone Widget' },
    command: 'tlb-clone'
  },
   {
    attributes: { 'class': 'fa fa-trash', title: 'Delete Widget' },
    command: 'tlb-delete'
  }
]
```

Example output:

``` html
<div class="gjs-toolbar" style="pointer-events: all; top: 132px; left: 1035px;">
  <div>
    <div class="fa fa-pencil gjs-toolbar-item" title="Configure this Widget"></div>
    <div class="fa fa-arrows gjs-toolbar-item" title="Move Widget"></div>
    <div class="fa fa-clone gjs-toolbar-item" title="Clone Widget"></div>
    <div class="fa fa-trash gjs-toolbar-item" title="Delete Widget"></div>
  </div>
</div>
```

**Comment by artf** [comment]
Thanks @thecodefish but this should already work because of this:
```js
attributes() {
   return this.model.get('attributes');
},
```

**Comment by thecodefish** [comment]
It doesn't, from what I've seen. I've added the title attribute to my config and nothing gets rendered without my change.

**Comment by artf** [comment]
Seems to work properly on my side, can I see your code example?

**Comment by thecodefish** [comment]
.. I stand corrected, sorry. I upgraded from an older version around the same time I was testing this so I must have been testing against the old version. I've done a new test against the latest version (without any of my modifications) and the toolbar title is working fine. I guess this PR isn't needed after all - sorry for wasting your time!

**Comment by artf** [comment]
no problem :)

**Pull request closed without merging**
