### PR TITLE
Refactor Storage Manager

### PR DESCRIPTION
**Pull request by artf**
This PR refactors the current Storage Manager and unfortunately introduces some necessary breaking changes in order to bring consistency across various storages (custom and built-in), especially with methods responsible for storing/loading editor data.

# Project Data
The important change is the introduction of the project data concept. This concept was actually already in place (the JSON you use to store/load pages/assets/etc.) but it was quite inconsistent (eg. stored differently on `local`/`remote`), now all the storages will exchange the same JSON object. For example, if previously we were storing local data in this way:
```js
localStorage.setItem(id + 'assets', JSON.stringify(assets));
localStorage.setItem(id + 'styles', JSON.stringify(styles));
```
Now the localStorage will simply store the project data object:
```js
localStorage.setItem(localKey, JSON.stringify(projectData));
```
You can easily get/load the project data manually with the new top API
```js
const projectData = editor.getProjectData();
// ...
editor.loadProjectData(projectData);
```

# Breaking changes
Here below you can find all the breaking changes of this PR, but we highly recommend checking out the [new Storage module documentation](https://github.com/artf/grapesjs/blob/7db3c77ffe6e9ecc8a931eaeb0cea4baa2f3899d/docs/modules/Storage.md) which also shows some common use cases and will be helpful in the upgrade process.
* `editor.store(currentStorageOptions)` and `editor.load(currentStorageOptions)` are now asynchronous methods and returns respectivly the stored and loaded project data (their first argument is not a callback anymore).
* Storage Manager methods `store`/`load` are also asynchronous now and the signature of their arguments is also changed.
* Storage API for adding custom storages is also changed.
  Before
  ```js
  editor.StorageManager.add('new-storage-id', {
    load(keys, clb, clbErr) {...},
    store(data, clb, clbErr) {...},
  }
  ```
  After
  ```js
  editor.StorageManager.add('new-storage-id', {
    async load(storageOptions) {...},
    async store(data, storageOptions) {...},
  }
  ```
* Changed StorageManager configuration. Now all storage type options are moved in their correspective `config.storageManager.options[STORAGE_TYPE]` default configurations.
  `storageManager.checkLocal` -> `storageManager.options.local.checkLocal`
  `storageManager.headers` -> `storageManager.options.remote.headers`
  `storageManager.urlStore` -> `storageManager.options.remote.urlStore`
  `storageManager.urlLoad` -> `storageManager.options.remote.urlLoad`
  `storageManager.contentTypeJson` -> `storageManager.options.remote.contentTypeJson`
  `storageManager.credentials` -> `storageManager.options.remote.credentials`
  `storageManager.fetchOptions` -> `storageManager.options.remote.fetchOptions`
* Removed `config.domComponents.storeWrapper` options. The project data will always store the wrapper of your pages.
*  Removed following configurations from StorageManager: `storeHtml`, `storeCss`, `storeComponents`, `storeStyles`, `beforeSend`, `onComplete`, `params`. The project data JSON doesn't extract any HTML/CSS from your pages anymore, but you're still able to extend your storages in order to enrich your data.

### CODE REVIEW

**Comment by lofcz** [comment]
Does this affect how assets are stored too?

**Comment by artf** [comment]
@lofcz keys won't be prefixed anymore (eg. `gjs-assets`) but still, it will be able to load them.

**Comment by clonefunnels** [comment]
Please help me understand how to fix everything that this update broke.  I don't understand why you wouldn't make it compatible with the old way.  But please tell me what I need to change from this example:

storageManager: {
	type: 'remote',    
    urlStore: 'save.php',
    urlLoad: 'load.php',
    storeComponents: true, // Enable/Disable storing of components in JSON format
    storeStyles: true,     // Enable/Disable storing of rules/style in JSON format
    storeHtml: true,        // Enable/Disable storing of components as HTML string
     storeCss: true,
	 stepsBeforeSave: 1,
    autosave: true,
    autoload: true,
	contentTypeJson: true,
	json_encode:{
        'components': [],
        'css': [],
        'html': [],
        'style': []
        }
    
  },

**Comment by artf** [comment]
@clonefunnels please spend a bit of time reading the [remote storage setup](https://grapesjs.com/docs/modules/Storage.html#setup-remote-storage). If something is not working please show your refactored code. If you don't have time to read and update, you can still use the old version.

**Comment by clonefunnels** [comment]
> @clonefunnels please spend a bit of time reading the [remote storage setup](https://grapesjs.com/docs/modules/Storage.html#setup-remote-storage). If something is not working please show your refactored code. If you don't have time to read and update, you can still use the old version.

I have read all through this tonight and attempted your code over and over again.  When I try with the const it completely kills it.  I assume because your demo that I'm copying most of the code uses var instead.

When I substitute with VAR it just kills everything inside the editor and gives a blank brown screen.

Could you please just tell me what to replace this code with:

var lp = './img/';
var plp = 'https://via.placeholder.com/350x250/';
var editor = grapesjs.init({
storageManager: {
type: 'remote',
urlStore: 'save.php',
urlLoad: 'load.php',
storeComponents: true, // Enable/Disable storing of components in JSON format
storeStyles: true, // Enable/Disable storing of rules/style in JSON format
storeHtml: true, // Enable/Disable storing of components as HTML string
storeCss: true,
stepsBeforeSave: 1,
autosave: true,
autoload: true,
contentTypeJson: true,
json_encode:{
'components': [],
'css': [],
'html': [],
'style': []
}

},

**Comment by clonefunnels** [comment]
I tried to just use the old version, but I noticed today that it removes the mobile devices style every time it loads.  So I have to update.

**Comment by clonefunnels** [comment]
I have wasted about 50 hours on this.  For you it would probably take 2 minutes to tell me exactly what code I need.

**Pull request merged**
