### PR TITLE
webpack resolve modules src removed

### PR DESCRIPTION
**Pull request by ateshuseyin**
In this PR, I removed local requires as modules which I described before in #369. 

related to #369

### CODE REVIEW

**Comment by artf** [comment]
Thanks @ateshuseyin 
I'm not a big fan of `../../` are ugly and don't even scale well, maybe we can use npm local modules?!?
eg. 
```js
“dependencies”: {
     ...
   “gjs”: “file:src”,
 }
```

**Comment by artf** [comment]
any update @ateshuseyin?

**Comment by ateshuseyin** [comment]
I tried local modules with webpack but it cannot resolve local modules without defining resolve statement in webpack config.

You are right `../..` are ugly but it is just the solution.

**Comment by artf** [comment]
well, I think it's possible to create an alias for the `gjs` module in webpack config :)

**Comment by artf** [comment]
By reading this https://gist.github.com/branneman/8048520 seems like there are no solid solutions for this issue...

**Comment by tommedema** [comment]
@artf I realize this is from 2017, but the `var Article = require.main.require('app/models/article');` solution seems pretty solid to me.

**Comment by artf** [comment]
@tommedema webpack supports `require.main` but not `require.main.require`

**Comment by Piterden** [comment]
Why not use alias like the next inside a webpack's config?
```js
const path = require('path')

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

module.exports = {
  resolve: {
    alias: {
      '@': resolve('src'),
    },
  },
}
```
then import it like:
```js
import ItemView from '@/navigator/view/ItemView.js'
```

**Comment by artf** [comment]
@Piterden thanks for the suggestion but how exactly would you implement it with npm as there is no concept of aliases?

**Comment by Piterden** [comment]
https://www.npmjs.com/package/module-alias

**Comment by artf** [comment]
Well cool, but that warning basically discourages the main point of the PR, using grapesjs from source (usually inside other npm modules) :(

**Comment by Piterden** [comment]
Nude node is so uncomfortable )))

PS I don't know why, but I use only `index.js` files under `src` for my last projects...

**Pull request closed without merging**
