### PR TITLE
Pass element in config

### PR DESCRIPTION
**Pull request by A----**
Allow user to pass an HTML node instead of a selector for the container configuration.

Frameworks like Angular asks of their components to be reusable. Basically, you would to this instead of relying on a selector:

# Template
```html
<div #grapejs></div>
```

# Component
```typescript
@Component({
  […]
})
export class MyGrapeJSComponent implements AfterViewInit {

  @ViewChild('grapesjs') grapesjs;
  private editor: any;

  ngAfterViewInit() {
    this.editor = grapesjs.init({
      container: this.grapesjs.nativeElement // Reference to the DOM node
    });
  }

}
```

### CODE REVIEW

**Comment by A----** [comment]
I did not see other places where `container` is used except one time where `el` was checked first, but that means that you can't rely for `container` to be a string anymore.

**Comment by suchithmahadi** [comment]
Artur Arseniev
Need you help in a Custom Component&JS, Please help me out

**Comment by artf** [comment]
thanks @A---- absolutely a must-have option, don't know why I haven't done this before :D

**Comment by suchithmahadi** [comment]
Can you guide me to do a custom component block for Google Chart ?

**Comment by artf** [comment]
wtf @suchithmahadi stop posting here, your problem it's not related with this PR...

**Comment by A----** [comment]
Thanks for the quick merge!

**Comment by artf** [comment]
@A---- no problem thanks to you, by the way, don't run `npm run build` for PRs as you get useless conflicts with minified files 😬

**Comment by A----** [comment]
I thought so too, I followed https://github.com/artf/grapesjs#development
Also I needed a compiled version for tests.

Maybe remove the `v:patch` from the `build` goal and change the readme?

**Comment by artf** [comment]
> Also I needed a compiled version for tests

You can run `npm test` for tests

The problem is not with `v:patch` but with the building itself, you may need to build because you need your custom minified GrapesJS but for PRs I think it's just not necessary. Maybe I should just add `Don't build for PRs`?!?  🤔

**Pull request merged**
