### PR TITLE
Refactor ‘open-assets’ editor command to permit arbitrary file types

### PR DESCRIPTION
**Pull request by tomichal**
The file types can be passed as a config option for an asset type in which case the types will be used to limit the accepted file type when uploading new files in the asset manager.
(See #985 for motivation for this change).

### CODE REVIEW

**Comment by tomichal** [comment]
Sounds good @artf , I'll update the pull request with the change you mentioned.

**Comment by artf** [comment]
> you don't feel like defining the type of accepted files should belong in the definition of the asset manager asset type?

Exactly, for instance, this will allow showing one kind of type but accepting a more generic one

**Comment by tomichal** [comment]
Made changes per your suggestion @artf (sorry it took so long)

**Comment by artf** [comment]
Thanks @tomichal 👍

**Pull request merged**
