### PR TITLE
Panels API - added removeButton and removePanel 

### PR DESCRIPTION
**Pull request by arthuralmeidap**
Hi @artf ,

  This PR is related to the issue #504.
  Take a look and check what you think about it.

### CODE REVIEW

**Comment by artf** [comment]
Thanks Arthur, for the PR and your clean work :)

**Comment by milapshah15** [comment]
I am trying to use 

//get Panel Object
var panelObj = panelManager.getPanel('options');

//Remove unwanted buttons
panelObj.get('buttons').remove('preview');

It is not removing the button.Am I doing anything wrong?

Warm regards
Milap

**Comment by artf** [comment]
@milapshah15 `panelManager.removeButton('options', 'preview')`

**Comment by milapshah15** [comment]
@artf  it says Panalmanager. removeButton is not a function

**Pull request merged**
